### PR TITLE
implemented Bertozzi (2020) close #99

### LINKED ISSUE #99: Add Bertozzi et al. (2020)
https://www.pnas.org/content/117/29/16732

### PR DESCRIPTION
**Pull request by vanako**

### CODE REVIEW

**Comment by vanako** [comment]
Hi @LeonardSchmiester , thank you for adding me as a collaborator. If I understand correctly, the first test fails because pandas v. 1.2.0 could not be found( https://travis-ci.com/github/Benchmarking-Initiative/Benchmark-Models-PEtab/builds/213024187#L217 ). Can I do something about this? If yes, I would appreciate your help with this :-)

**Comment by yannikschaelte** [comment]
The problem is that petab requires pandas>=1.2.0, which only exists on python>=3.7, therefore you need to change https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/blob/master/.travis.yml#L2 to 3.7, or better 3.8, maybe it works then.

**Review by LeonardSchmiester — APPROVED** [review]

**Comment by LeonardSchmiester** [comment]
@vanako feel free to squash and merge :+1:

**Comment by LeonardSchmiester** [comment]
@vanako this can be merged then, right?!

**Comment by vanako** [comment]
sorry for the delay!! :see_no_evil:

**Pull request merged**
