### PR TITLE
Added Froehlich Cell Systems 2018 model. Closes #78

### LINKED ISSUE #78: Add Fröhlich et al. (2018)
https://www.cell.com/cell-systems/pdfExtended/S2405-4712(18)30438-1

### PR DESCRIPTION
**Pull request by LeonardSchmiester**

### CODE REVIEW

**Comment by stephanmg** [comment]
Looks good to me.

**Review by stephanmg — APPROVED** [review]
Looks good to me.

**Comment by FFroehlich** [comment]
Really hard to judge for me as the files are so gigantic. How was this validated that implementation is correct?

**Comment by stephanmg** [comment]
I merely remember by private communication with @LeonardSchmiester that he did validate simulations prior to opening this PR.

**Review by plakrisenko — APPROVED** [review]

**Comment by dilpath** [comment]
Thanks to @plakrisenko for checking. Compared to the original implementation, the following files are the same or negligibly different
- SBML (now with different metadata: model ID and model name)
- experimental conditions
- observables
- measurements (now with a `datasetId` column)

The parameters table has new nominal values, which presumably were both the output of optimization and used to produce the simulated data.

So I guess this implementation is "corrrect", in that it matches the original implementation.

**Review by FFroehlich — APPROVED** [review]

**Pull request merged**
