### PR TITLE
Make Bertozzi consistent

### PR DESCRIPTION
**Pull request by stephanmg**
Make Bertozzi's `Susceptible_to_Infected` consistent.

### CODE REVIEW

**Comment by dilpath** [comment]
What is inconsistent? The Susceptible -> Infected reaction is not reversible, right?

**Comment by stephanmg** [comment]
```
Susceptible_to_Infected
Rate Law for Susceptible_to_Infected_1
The kinetic function is marked as irreversible but at least one of its variables is labeled as product. 
```

**Comment by dilpath** [comment]
Is this forbidden in SBML? The interaction between `susceptible + infected` causes `susceptible -> infected`, not `infected -> susceptible`, right?

**Comment by stephanmg** [comment]
> Is this forbidden in SBML? The interaction between `susceptible + infected` causes `susceptible -> infected`, not `infected -> susceptible`, right?

Ah, the interaction should be non-reversible true. So what about this message from COPASI/SBML validator? False-positive warning?

**Comment by dilpath** [comment]
> False-positive warning?

I'm not sure, but this is my guess -- maybe it's unusual to see direct positive-feedback with the product in the kinetic law.

**Comment by FFroehlich** [comment]
I think the rate law should be `susceptible + infected -> susceptible + susceptible` rather than `infected -> susceptible`

**Comment by dilpath** [comment]
> I think the rate law should be `susceptible + infected -> infected + infected` rather than `susceptible -> infected`

Ah thanks, makes sense, done in #222 , where the problem is further modified to be a more reasonable parameter estimation problem.

**Comment by stephanmg** [comment]
Can this issue then be closed in light of additional fixes in #222?

**Pull request closed without merging**
