### PR TITLE
Fix Alkan_SciSignal2018

### PR DESCRIPTION
**Pull request by dilpath**
Resolves errors of this kind when running the linter.

```
Traceback (most recent call last):
  File "venv/bin/petablint", line 8, in <module>
    sys.exit(main())
  File "venv/lib/python3.8/site-packages/petab/petablint.py", line 164, in main
    ret = petab.lint.lint_problem(problem)
  File "venv/lib/python3.8/site-packages/petab/lint.py", line 764, in lint_problem
    check_measurement_df(problem.measurement_df, problem.observable_df)
  File "venv/lib/python3.8/site-packages/petab/lint.py", line 177, in check_measurement_df
    measurements.assert_overrides_match_parameter_count(
  File "venv/lib/python3.8/site-packages/petab/measurements.py", line 314, in assert_overrides_match_parameter_count
    actual = len(split_parameter_replacement_list(
  File "venv/lib/python3.8/site-packages/petab/measurements.py", line 241, in split_parameter_replacement_list
    return list(map(convert_and_check, result))
  File "venv/lib/python3.8/site-packages/petab/measurements.py", line 236, in convert_and_check
    raise ValueError(
ValueError: The value '' in the parameter replacement list 'scale_patm_au;' is neither a number, nor a valid parameter ID.
```

### CODE REVIEW

**Comment by elbaraim** [comment]
Thanks @dilpath for the fix!
I have however noticed some measurements with empty values in the `measurement` column and they seem to be repeated.
e.g.


pDNAPK_au |   | model1_data22 |   | 0.25 | scale_pdnapk_au | sd_pdnapk_au | model1_data22_pdnapk_au
-- | -- | -- | -- | -- | -- | -- | --


I guess those can be removed since they seem to be duplicated entries @LaraFuhrmann any thoughts?

**Comment by dilpath** [comment]
> Thanks @dilpath for the fix!
> I have however noticed some measurements with empty values in the `measurement` column and they seem to be repeated.
> e.g.
> pDNAPK_au 	  	model1_data22 	  	0.25 	scale_pdnapk_au 	sd_pdnapk_au 	model1_data22_pdnapk_au
> 
> I guess those can be removed since they seem to be duplicated entries @LaraFuhrmann any thoughts?

Good catch! Not all are duplicates.
https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/blob/4aa5e4fce9d23910b043791ada58bc371c425618/Benchmark-Models/Alkan_SciSignal2018/measurementData_Alkan_SciSignal2018.tsv#L1618

**Comment by elbaraim** [comment]
shall we just remove the repeated empty entries? even the `datasetId` is identical
those that are not repeated, but still empty we can keep just to be safe

**Comment by dilpath** [comment]
> shall we just remove the repeated empty entries? even the `datasetId` is identical
> those that are not repeated, but still empty we can keep just to be safe

Sure, should be done now. Would be great to get feedback from @LaraFuhrmann when possible, but will merge now if approved.

**Comment by elbaraim** [comment]
> > shall we just remove the repeated empty entries? even the `datasetId` is identical
> > those that are not repeated, but still empty we can keep just to be safe
> 
> Sure, should be done now. Would be great to get feedback from @LaraFuhrmann when possible, but will merge now if approved.

@dilpath could you also correct the simulatedData file? also there se semicolons are present and the weird duplicated 😓

**Comment by LaraFuhrmann** [comment]
Thanks for taking care of that. I do not recall any reason for the empty (or duplicate) `measurement` cells.

**Comment by dilpath** [comment]
> Thanks for taking care of that. I do not recall any reason for the empty (or duplicate) `measurement` cells.

Thanks for the feedback! Currently only "duplicated and empty" measurements are removed ("unique and empty" measurements are kept, not sure what they are for though).

> > > shall we just remove the repeated empty entries? even the `datasetId` is identical
> > > those that are not repeated, but still empty we can keep just to be safe
> > 
> > 
> > Sure, should be done now. Would be great to get feedback from @LaraFuhrmann when possible, but will merge now if approved.
> 
> @dilpath could you also correct the simulatedData file? also there the semicolons are present and the weird duplicated sweat
> 
> EDIT: also the index column could be removed in the simulatedData

Thanks, done now.

**Comment by elbaraim** [comment]
sorry for disturbing, but i have noticed as well that some exp. conditions are duplicated 😓 
e.g. conditions with all inputs set to zero
... `model1_data45`, `model1_data59` ...

**Review by LaraFuhrmann — APPROVED** [review]
Looks all good to me. Thanks for fixing.

**Review by elbaraim — APPROVED** [review]

**Pull request merged**
